### ISSUE TITLE
When linking to Social Media, preview description still reads "Coming March 2021"

### ISSUE THREAD

**Issue by MissMadore** [algonquindesign-grads/2021#115] opened 2021-04-20 15:55 UTC
Can someone please advise on where that information is noted? @thomasjbradley @MacKenzieRose

**Comment by MacKenzieRose** [comment] 2021-04-20 16:04
That content is from the Coming Soon site, and is probably just cached elsewhere on servers. (Unless I hecked up the SEO stuff in this repository, which is also possible 🤡 )

**Comment by thomasjbradley** [comment] 2021-04-20 16:35
Yep, a cache thing. I just cleared Facebook’s sharing cache so it should be good now.

**Comment by MissMadore** [comment] 2021-04-20 17:03
Is this a step that I need to take locally? :')

**Comment by thomasjbradley** [comment] 2021-04-20 17:09
Nope, shouldn’t be. Is your FB still wrong?

**Comment by HannahDelaney** [comment] 2021-04-20 17:22
Yes, it still shows "Coming March 2021" on the FB messenger preview.

**Comment by MissMadore** [comment] 2021-04-20 18:01
& instagram shares

**Comment by MacKenzieRose** [comment] 2021-04-21 15:49
This issue resolved on my end; how is it for you now, @MissMadore ?

**Comment by thomasjbradley** [comment] 2021-04-21 15:49
Seems to be working today. Any one else confirm?

**Comment by thomasjbradley** [comment] 2021-04-21 15:49
Nevermind, I see @MacKenzieRose confirmed.

I think we can close this.

**Closed as completed** 2021-04-21 15:56 UTC
Labels: question

**Comment by MissMadore** [comment] 2021-04-21 16:26
I am still seeing the wrong description, but I hope it's just me :')
